/*
 * generated by Xtext 2.10.0
 */
package eu.numberfour.n4js.ui;

import com.google.inject.Injector;
import eu.numberfour.n4js.ui.internal.N4jsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class N4JSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return N4jsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return N4jsActivator.getInstance().getInjector(N4jsActivator.EU_NUMBERFOUR_N4JS_N4JS);
	}
	
}
